import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/seo-config";

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticPages: {
    path: string;
    changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"];
    priority: number;
  }[] = [
    // Core
    { path: "/", changeFrequency: "weekly", priority: 1.0 },
    { path: "/about", changeFrequency: "monthly", priority: 0.7 },
    { path: "/how-it-works", changeFrequency: "monthly", priority: 0.8 },
    { path: "/faq", changeFrequency: "monthly", priority: 0.7 },
    { path: "/features", changeFrequency: "monthly", priority: 0.8 },
    { path: "/pricing", changeFrequency: "monthly", priority: 0.7 },
    { path: "/contact", changeFrequency: "yearly", priority: 0.4 },
    { path: "/about", changeFrequency: "monthly", priority: 0.7 },
    { path: "/terms", changeFrequency: "yearly", priority: 0.3 },
    { path: "/privacy", changeFrequency: "yearly", priority: 0.3 },
    { path: "/accessibility", changeFrequency: "yearly", priority: 0.3 },
    { path: "/changelog", changeFrequency: "monthly", priority: 0.4 },
    { path: "/glossary", changeFrequency: "monthly", priority: 0.5 },
    { path: "/help", changeFrequency: "monthly", priority: 0.6 },

    // Tool landing pages
    { path: "/split-receipt", changeFrequency: "monthly", priority: 0.9 },
    { path: "/bill-splitter", changeFrequency: "monthly", priority: 0.9 },
    { path: "/tip-calculator", changeFrequency: "monthly", priority: 0.8 },
    { path: "/venmo-calculator", changeFrequency: "monthly", priority: 0.8 },
    { path: "/restaurant-bill-calculator", changeFrequency: "monthly", priority: 0.8 },
    { path: "/check-splitter", changeFrequency: "monthly", priority: 0.9 },
    { path: "/expense-splitter", changeFrequency: "monthly", priority: 0.8 },
    { path: "/going-dutch", changeFrequency: "monthly", priority: 0.7 },
    { path: "/receipt-scanner", changeFrequency: "monthly", priority: 0.8 },
    { path: "/splitwise-alternative", changeFrequency: "monthly", priority: 0.9 },
    { path: "/cash-app-split", changeFrequency: "monthly", priority: 0.7 },
    { path: "/zelle-split", changeFrequency: "monthly", priority: 0.7 },
    { path: "/paypal-split", changeFrequency: "monthly", priority: 0.7 },
    { path: "/group-expense-calculator", changeFrequency: "monthly", priority: 0.8 },
    { path: "/dinner-split-calculator", changeFrequency: "monthly", priority: 0.8 },

    // Compare hub + pages
    { path: "/compare", changeFrequency: "monthly", priority: 0.7 },
    { path: "/compare/jig-vs-splitwise", changeFrequency: "monthly", priority: 0.7 },
    { path: "/compare/jig-vs-tab", changeFrequency: "monthly", priority: 0.7 },
    { path: "/compare/jig-vs-venmo", changeFrequency: "monthly", priority: 0.7 },
    { path: "/compare/jig-vs-plates", changeFrequency: "monthly", priority: 0.6 },
    { path: "/compare/jig-vs-tricount", changeFrequency: "monthly", priority: 0.6 },
    { path: "/compare/jig-vs-splid", changeFrequency: "monthly", priority: 0.6 },
    { path: "/compare/jig-vs-easy-check-splitter", changeFrequency: "monthly", priority: 0.6 },
    { path: "/compare/jig-vs-onesplit", changeFrequency: "monthly", priority: 0.6 },
    { path: "/compare/jig-vs-splitty", changeFrequency: "monthly", priority: 0.6 },

    // Use cases
    { path: "/use-cases", changeFrequency: "monthly", priority: 0.7 },
    { path: "/use-cases/restaurants", changeFrequency: "monthly", priority: 0.7 },
    { path: "/use-cases/roommates", changeFrequency: "monthly", priority: 0.7 },
    { path: "/use-cases/travel", changeFrequency: "monthly", priority: 0.7 },
    { path: "/use-cases/groceries", changeFrequency: "monthly", priority: 0.7 },
    { path: "/use-cases/office-lunches", changeFrequency: "monthly", priority: 0.6 },
    { path: "/use-cases/weddings", changeFrequency: "monthly", priority: 0.6 },
    { path: "/use-cases/parties", changeFrequency: "monthly", priority: 0.6 },
    { path: "/use-cases/dates", changeFrequency: "monthly", priority: 0.6 },

    // Blog hub
    { path: "/blog", changeFrequency: "weekly", priority: 0.8 },
  ];

  const blogSlugs = [
    // The Basics
    "how-to-split-a-restaurant-bill",
    "fair-bill-splitting-methods",
    "why-even-splits-arent-fair",
    "best-bill-splitting-apps",
    "how-to-calculate-tax-and-tip-per-person",
    "receipt-splitting-etiquette",
    "digital-receipt-management",
    "why-receipt-scanning-is-the-future",
    // Restaurants & Food
    "group-dining-guide",
    "how-to-split-a-sushi-bill",
    "how-to-split-a-pizza-bill",
    "how-to-split-a-brunch-bill",
    "how-to-split-a-bar-tab",
    "how-to-split-a-food-delivery-order",
    "how-to-split-a-buffet-bill",
    "how-to-split-a-wine-tasting-bill",
    "how-to-handle-separate-checks",
    "how-to-split-a-bbq-restaurant-bill",
    "how-to-split-a-tasting-menu-bill",
    "when-restaurants-wont-split-the-bill",
    "how-to-split-shared-appetizers",
    "how-to-split-a-large-group-dinner",
    "how-to-split-a-costco-run",
    "how-to-split-a-byob-restaurant-bill",
    "splitting-bills-with-dietary-restrictions",
    "who-pays-for-table-appetizers",
    "how-to-split-dessert-costs",
    "how-to-split-a-meal-prep-grocery-haul",
    // Occasions & Events
    "how-to-split-a-birthday-dinner-bill",
    "how-to-split-bachelorette-party-expenses",
    "how-to-split-bachelor-party-expenses",
    "how-to-split-baby-shower-costs",
    "how-to-split-holiday-dinner-costs",
    "how-to-split-thanksgiving-dinner-expenses",
    "how-to-split-christmas-party-costs",
    "how-to-split-new-years-eve-dinner-bill",
    "how-to-split-super-bowl-party-food-costs",
    "how-to-split-expenses-at-a-music-festival",
    "how-to-split-expenses-at-a-sporting-event",
    "how-to-split-a-wedding-reception-dinner",
    "how-to-split-a-graduation-dinner-bill",
    "how-to-split-reunion-dinner-bills",
    "how-to-split-a-going-away-party-bill",
    "how-to-split-office-party-expenses",
    "how-to-split-potluck-shopping-costs",
    "how-to-split-a-group-gift-purchase",
    "how-to-split-costs-for-a-dinner-party",
    "how-to-split-a-tailgate-party-bill",
    // Relationships & Living
    "how-couples-split-bills-fairly",
    "how-to-split-bills-when-you-earn-more",
    "money-conversations-every-couple-should-have",
    "financial-expectations-before-moving-in",
    "splitting-bills-when-living-together",
    "splitting-bills-after-a-breakup",
    "how-to-split-bills-with-roommates",
    "splitting-bills-as-roommates",
    "splitting-household-expenses-system",
    "how-to-split-utility-bills-with-roommates",
    "how-to-split-a-joint-grocery-order",
    "how-to-split-a-costco-membership",
    "splitting-bills-on-a-first-date",
    "should-you-split-on-a-second-date",
    "splitting-expenses-in-a-new-relationship",
    "how-college-students-split-bills",
    "how-to-split-bills-in-a-college-dorm",
    "splitting-bills-when-one-person-is-unemployed",
    "how-to-split-shared-subscriptions",
    "splitting-amazon-prime-membership",
    "how-to-split-streaming-service-costs",
    // Travel & Technology
    "how-to-split-airbnb-costs",
    "how-to-split-hotel-bills-group-trip",
    "how-to-split-expenses-on-a-road-trip",
    "how-to-split-expenses-on-a-cruise",
    "how-to-split-bills-in-foreign-currency",
    "splitting-group-travel-expenses-in-europe",
    "how-to-track-group-expenses-during-travel",
    "splitting-expenses-when-some-paid-cash",
    "how-to-split-doordash-uber-eats-orders",
    "how-to-split-grubhub-orders-at-the-office",
    "how-to-use-apple-pay-to-split-bills",
    "how-to-split-bills-using-google-pay",
    "best-way-to-split-bills-2026",
    "how-technology-changed-bill-splitting",
    "ai-receipt-scanning-vs-ocr",
    "history-of-going-dutch",
    "why-venmo-took-over-bill-splitting",
    "how-gen-z-splits-bills",
    "bill-splitting-cultural-differences",
    // Payment Apps
    "splitting-bills-with-venmo",
    "venmo-vs-zelle-vs-cashapp-for-splitting",
    "how-to-use-venmo-for-group-expenses",
    // Etiquette & Money
    "how-to-calculate-tip-for-large-groups",
    "how-to-handle-auto-gratuity",
    "service-charge-vs-tip-difference",
    "when-someone-ordered-way-more",
    "what-to-do-when-friend-never-pays-back",
    "how-to-remind-someone-they-owe-you",
    "how-to-ask-friends-to-pay-you-back",
    "splitting-bills-with-bad-with-money-friend",
    "how-to-split-bills-on-a-budget",
    "psychology-of-splitting-bills",
    "non-drinker-splitting-bills",
    "how-to-split-alcohol-vs-non-alcohol",
    "etiquette-of-rounding-up-when-splitting",
    // Practical Guides
    "how-to-split-a-receipt-with-discounts",
    "how-to-split-when-someone-used-gift-card",
    "how-to-handle-bill-splitting-dispute",
    "how-to-split-a-very-long-receipt",
    "tax-and-service-charges-international-splitting",
    "splitting-expenses-for-business-meals",
    "bill-splitting-for-freelancers",
    "tracking-shared-business-expenses",
  ];

  return [
    ...staticPages.map(({ path, changeFrequency, priority }) => ({
      url: `${SITE_URL}${path}`,
      lastModified: now,
      changeFrequency,
      priority,
    })),
    ...blogSlugs.map((slug) => ({
      url: `${SITE_URL}/blog/${slug}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    })),
  ];
}
